package eu.mihaibadea.requestlab.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Light scheme — forest green brand palette
val LightPrimary             = Color(0xFF1B6B42)
val LightOnPrimary           = Color(0xFFFFFFFF)
val LightPrimaryContainer    = Color(0xFF9AF4C2)
val LightOnPrimaryContainer  = Color(0xFF002112)
val LightSecondary           = Color(0xFF4D6E5A)
val LightOnSecondary         = Color(0xFFFFFFFF)
val LightSecondaryContainer  = Color(0xFFCFE9D7)
val LightOnSecondaryContainer= Color(0xFF0A1F12)
val LightTertiary            = Color(0xFF3E6374)
val LightOnTertiary          = Color(0xFFFFFFFF)
val LightTertiaryContainer   = Color(0xFFC2E8FB)
val LightOnTertiaryContainer = Color(0xFF001F2B)
val LightError               = Color(0xFFBA1A1A)
val LightOnError             = Color(0xFFFFFFFF)
val LightErrorContainer      = Color(0xFFFFDAD6)
val LightOnErrorContainer    = Color(0xFF410002)
val LightBackground          = Color(0xFFF4FBF4)
val LightOnBackground        = Color(0xFF1A1C1A)
val LightSurface             = Color(0xFFF4FBF4)
val LightOnSurface           = Color(0xFF1A1C1A)
val LightSurfaceVariant      = Color(0xFFD3E8D8)
val LightOnSurfaceVariant    = Color(0xFF3E4D41)
val LightSurfaceTint         = Color(0xFF1B6B42)
val LightOutline             = Color(0xFF6E7E70)
val LightOutlineVariant      = Color(0xFFB8CDB9)
val LightInverseSurface      = Color(0xFF2E312E)
val LightInverseOnSurface    = Color(0xFFEEF5ED)
val LightInversePrimary      = Color(0xFF7DD7A4)
val LightScrim               = Color(0xFF000000)

// Dark scheme
val DarkPrimary              = Color(0xFF7DD7A4)
val DarkOnPrimary            = Color(0xFF003921)
val DarkPrimaryContainer     = Color(0xFF005231)
val DarkOnPrimaryContainer   = Color(0xFF9AF4C2)
val DarkSecondary            = Color(0xFFB3CCBA)
val DarkOnSecondary          = Color(0xFF1F3527)
val DarkSecondaryContainer   = Color(0xFF35503E)
val DarkOnSecondaryContainer = Color(0xFFCFE9D7)
val DarkTertiary             = Color(0xFFA5CCDF)
val DarkOnTertiary           = Color(0xFF053445)
val DarkTertiaryContainer    = Color(0xFF244C5D)
val DarkOnTertiaryContainer  = Color(0xFFC2E8FB)
val DarkError                = Color(0xFFFFB4AB)
val DarkOnError              = Color(0xFF690005)
val DarkErrorContainer       = Color(0xFF93000A)
val DarkOnErrorContainer     = Color(0xFFFFDAD6)
val DarkBackground           = Color(0xFF0C1410)
val DarkOnBackground         = Color(0xFFE2E9E1)
val DarkSurface              = Color(0xFF0C1410)
val DarkOnSurface            = Color(0xFFE2E9E1)
val DarkSurfaceVariant       = Color(0xFF3E4D41)
val DarkOnSurfaceVariant     = Color(0xFFB8CDB9)
val DarkSurfaceTint          = Color(0xFF7DD7A4)
val DarkOutline              = Color(0xFF839188)
val DarkOutlineVariant       = Color(0xFF3E4D41)
val DarkInverseSurface       = Color(0xFFE2E9E1)
val DarkInverseOnSurface     = Color(0xFF2E312E)
val DarkInversePrimary       = Color(0xFF1B6B42)
val DarkScrim                = Color(0xFF000000)
